apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    auth: "true"
    serving: "true"
    v3: "true"
resources:
  - subscription.yaml
  - operatorgroup.yaml
  - authorino
