apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  labels:
    distributedworkload: "true"
    v2: "true"
    v3: "true"
resources:
  - namespace.yaml
  - subscription.yaml
  - operatorgroup.yaml
